server:
  port: 8084

spring:
  application:
    name: auth-service
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
          max-wait: 2000ms

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS}
  refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS}

user-service:
  url: ${USER_SERVICE_URL}
  connect-timeout-ms: 2000
  read-timeout-ms: 5000
  internal-secret: ${INTERNAL_SECRET}

mfa:
  cache:
    ttl-seconds: 60
    key-prefix: "mfa:secret:"

springdoc:
  swagger-ui:
    enabled: ${SPRINGDOC_API_DOCS_SWAGGER_ENABLED:false}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never