apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: auth
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth-service
    {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.authService.port }}
      targetPort: {{ .Values.authService.port }}
      protocol: TCP
      name: http
