{{- if .Values.gateway.hpa.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: gateway
    {{- include "app.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
      {{- include "app.selectorLabels" . | nindent 6 }}
{{- end }}
