apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: mysql
    {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}
      protocol: TCP
      name: mysql
