server:
  port: 8085
spring:
  application:
    name: api-gateway-service
  threads:
    virtual:
      enabled: true

jwt:
  secret: ${JWT_SECRET}

gateway:
  routes:
    - prefix: /auth
      target: ${AUTH_SERVICE_URL}
    - prefix: /users
      target: ${USER_SERVICE_URL}
  public-paths:
    # Format: "METHOD:path"
    - "POST:/auth/login"
    - "POST:/auth/refresh"
    - "POST:/auth/mfa"
    - "POST:/auth/logout"
    - "POST:/users"
    - "POST:/users/code"
    - "POST:/users/activation"
    - "POST:/users/password/permission"
    - "POST:/users/password/reset"
    - "GET:/"
    - "GET:/actuator/health"
  admin-paths:
    - "PUT:/users/*/role"
  user-paths:
    - "POST:/users/*/mfa"
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "http://localhost:63342"
  forwarding:
    connect-timeout-ms: 2000
    read-timeout-ms: 10000
