apiVersion: v1
kind: Secret
metadata:
  name: security-platform-secrets
  namespace: security-platform
  labels:
    app.kubernetes.io/part-of: security-platform
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "CHANGE_ME"
  MYSQL_USER: "app_user"
  MYSQL_PASSWORD: "CHANGE_ME"
  SPRING_DATASOURCE_USERNAME: "app_user"
  SPRING_DATASOURCE_PASSWORD: "CHANGE_ME"
  REDIS_PASSWORD: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME_base64_encoded_512bit_key"
  INTERNAL_SECRET: "CHANGE_ME"
  MAIL_PASSWORD: ""
