apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-gateway
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: security-platform
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.apiGateway.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
