apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis
    {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      protocol: TCP
      name: redis
