apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword | quote }}
  mysql-user: {{ .Values.secrets.mysqlUser | quote }}
  mysql-password: {{ .Values.secrets.mysqlPassword | quote }}
  internal-secret: {{ .Values.secrets.internalSecret | quote }}
  mail-username: {{ .Values.secrets.mailUsername | quote }}
  mail-password: {{ .Values.secrets.mailPassword | quote }}
