apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth-service
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: auth-service
    app.kubernetes.io/part-of: security-platform
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.authService.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/instance: {{ .Release.Name }}
