apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: security-platform
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/part-of: security-platform
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/users_db?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_USERNAME: "firelight.code@gmail.com"
  MFA_ISSUER: "SecurityPlatform"
